packages:
  - "packages/core"
  - "packages/bindings/*"
  - "packages/clients/*"
  - "packages/tools/*"
  - "examples/*"

allowBuilds:
  esbuild: set this to true or false

onlyBuiltDependencies:
  - esbuild
